import { CvData } from "./types";

export const DEMO_CV: CvData = {
  personal: {
    name: "Jahid Hasan Milon",
    email: "jahidhasanmilon999@gmail.com",
    phone: "+880 1850-921919",
    location: "Dhaka, Bangladesh",
    linkedin: "linkedin.com/in/jahid-hasan-milon",
  },
  targetCountry: "DE",
  education: [
    {
      degree: "B.S. in Computer Science (Minor: Media and Communication)",
      institution: "Independent University, Bangladesh",
      location: "Dhaka, Bangladesh",
      start: "",
      end: "May 2025",
      details: "",
    },
    {
      degree: "Higher Secondary Certificate",
      institution: "Hazera-Taju Degree College",
      location: "Chittagong, Bangladesh",
      start: "",
      end: "2018",
      details: "",
    },
  ],
  experience: [
    {
      title: "Web Developer Intern",
      company: "Elsecode Tech",
      location: "Dhaka, Bangladesh",
      start: "Feb 2025",
      end: "Jun 2025",
      bullets: [
        "Built a basic e-commerce web application including product listings, shopping cart, and admin panel",
        "Contributed to frontend development tasks, improving UI and resolving bugs",
        "Collaborated with the development team on real-world web development workflows",
      ],
    },
    {
      title: "Founder",
      company: "Rubalif (Short News App)",
      location: "Dhaka, Bangladesh",
      start: "Jan 2021",
      end: "Jan 2025",
      bullets: [
        "Designed and launched Rubalif, a personalized short-news mobile app curating content from trustworthy media outlets",
        "Grew and maintained an active user base, handling product decisions, UX design, and content curation end-to-end",
      ],
    },
    {
      title: "Founder & Frontend Web Developer",
      company: "JhmHQ",
      location: "Dhaka, Bangladesh",
      start: "Jul 2020",
      end: "Present",
      bullets: [
        "Designed, developed, and published websites for nonprofits and small businesses using WordPress",
        "Optimized sites for SEO (RankMath), improving organic search rankings for clients",
        "Built custom themes and provided ongoing website maintenance and support",
      ],
    },
  ],
  skills: [
    "JavaScript",
    "PHP",
    "Java",
    "C++",
    "C#",
    "Python",
    "HTML5",
    "CSS3",
    "WordPress",
    "Laravel",
    "REST APIs",
    "MySQL",
    "Firebase",
    "Git",
    "Figma",
    "SEO (RankMath)",
  ],
};
